name: Dump Secret

on:
  workflow_dispatch:

jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - name: Dump
        env:
          SECRET: ${{ secrets.TEESCAN_PROXY_URL }}
        run: |
          echo "$SECRET" | base64
